version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    networks:
      - web
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tpdlqm88
    logging:
      options:
        max-size: 10m
        max-file: "13"
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgres/sql/postgresql.conf
  redis:
    image: redis:7.0.0
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - 8078:8078
networks:
  web:
    external: true
        
       